// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SimpleMsgSideView","status":true,"description":"at sideview battle, only display item/skill names.","parameters":{"displayAttack":"0","position":"1"}},
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}},
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"VPS - Dynamic Weather System","status":false,"description":"v4.0 RMMV 1.3.1 An extended weather system for RMMV with different effects and behaviors.","parameters":{"- WEATHER CUSTOMIZATION -":"","AutumnLeafSpeedX":"0","AutumnLeafSpeedY":"1","AutumnLeafOpacity":"1","SakuraSpeedX":"0","SakuraSpeedY":"1","SakuraOpacity":"1","BlowingSakuraSpeedX":"3","BlowingSakuraSpeedY":"3","BlowingSakuraOpacity":"1","CloverSpeedX":"0","CloverSpeedY":"1","CloverOpacity":"1","BlowingCloverSpeedX":"3","BlowingCloverSpeedY":"0","BlowingCloverOpacity":"1","BlowingAutumnSpeedX":"10","BlowingAutumnSpeedY":"0","BlowingAutumnOpacity":"1","-STORM CONTROL-":"","LightningDuration":"300000","LightningCounter":"10","ThunderclapAudio":"Thunder1","ThunderclapVolume":"100","ThunderclapPitch":"100","ThunderclapPan":"0","-WEATHER RESOURCES-":"","SnowballImage":"snowball","FlakeImage":"flake","BlizzardImage":"blizzard","IceImage":"ice","GlitterImage":"glitter","FireImage":"fire","LightImage":"light","MeteorImage":"meteor","LeafBladeImage":"leafblade","PollenImage":"pollen","FairydustImage":"fairydust","LeafImage":"leaf","AutumnLeafImage":"autumnleaf","SpringLeafImage":"springleaf","CloverImage":"clover","SakuraImage":"sakura","BubbleImage":"bubble","WingImage":"wing","WaterImage":"water"}}
];
